name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-gradle-project:
    runs-on: self-hosted
    steps:
    # gradle build
    # Use cache to decrease build time? 
    # This might help:
    # cache: gradle

    # Code for Github runner:
    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v3
    #   - name: Set up JDK 17
    #     uses: actions/setup-java@v3
    #     with:
    #       java-version: 17
    #       distribution: 'adopt'
    #       cache: gradle
    #   - name: Build with Gradle
    #     run: ./gradlew build --scan --no-daemon